### ISSUE TITLE
Not updating height properly

### ISSUE THREAD

**Issue by JoshuaKlassen** [Brightspace/user-tile#22]
It appears that when the information is loaded, the heights of the tiles don't update properly

see: https://github.com/Brightspace/parent-portal-ui/issues/79

**Comment by apalaniuk** [comment]
So, I think the height of the tiles updates correctly- it may be more related to containing elements not updating some properties in response to the tile's height increasing for some reason. It could be due to styling in this element, but looking on your computer at this problem, the tile itself seemed to have the correct height.

Or: It's hard to say that this is exactly what's happening, or that this component itself is the problem. But it's certainly involved in it.

**Comment by ryantmer** [comment]
@apalaniuk This one is also solved, correct? Or more accurately, the problem wasn't here after all?

**Comment by jstefaniuk-d2l** [comment]
This issue was with the parent-portal-ui repo and should be solved now, closing this issue 👍
